//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YURT_OTOMASYONU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        public int Id { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<int> OdaNo { get; set; }
        public Nullable<int> BuzdolabiSayisi { get; set; }
        public Nullable<int> YatakSayisi { get; set; }
        public Nullable<int> OdaId { get; set; }
    
        public virtual Dolap Dolap { get; set; }
        public virtual Masa Masa { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
        public virtual Yatak Yatak { get; set; }
    }
}
