//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YURT_OTOMASYONU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oda()
        {
            this.Envanter = new HashSet<Envanter>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<int> OdaNo { get; set; }
        public Nullable<int> BuzdolabiSayisi { get; set; }
        public Nullable<int> YatakSayisi { get; set; }
        public Nullable<int> OdaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envanter> Envanter { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
