//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YURT_OTOMASYONU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekListesi
    {
        public int Id { get; set; }
        public string Yemek1 { get; set; }
        public string Yemek2 { get; set; }
        public string Yemek3 { get; set; }
        public string Yemek4 { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
